# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/tag-publish/0.13.3/tag_publish/schema.json

docker:
  images:
    - name: camptocamp/qgis-server
      tags:
        - '{version}'
        - '{version}-debug'
        - '{version}-desktop'
dispatch:
  - {}
version:
  branch_to_version:
    - from: ([0-9]+.[0-9]+-gdal[0-9]+.[0-9]+)
      to: \1
    - from: master
      to: master
