ignored:
  - DL3003 # Use WORKDIR to switch to a directory
  - DL3008 # Pin versions in apt get install. Instead of `apt-get install <package>` use `apt-get install <package>=<version>`
  - DL3042 # Avoid use of cache directory with pip. Use `pip install --no-cache-dir <package>`
  - DL3059 # Multiple consecutive `RUN` instructions. Consider consolidation.
  - SC1091 # Not following: File not included in mock.
  - SC2164 # Use cd ... || exit in case cd fails.
