ignored:
  - DL3008 # pin version: https://github.com/hadolint/hadolint/wiki/DL3008
  - DL3003 # use workdir: https://github.com/hadolint/hadolint/wiki/DL3003
  - DL3059 # Multiple consecutive `RUN` instructions. Consider consolidation.
  - SC2164 # Use cd ... || exit in case cd fails.
