#!/bin/bash -eux

if [ "$#" -ne 1 ]; then
    echo "Usage: checkout_release.sh {BRANCH}"
    echo
    echo "Checkout the last tag matching final-* of the given branch"
    exit 1
fi

BRANCH=$1

git checkout "${BRANCH}"
git pull --rebase

echo
echo "Will build: -----------------------------------------"
git log -n 1 --decorate
echo "-----------------------------------------------------"
echo

git status
