---
name: Rebuild

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Rebuild
    timeout-minutes: 150

    strategy:
      fail-fast: false
      matrix:
        branch:
          - '3.4'
          - '3.10'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ matrix.branch }}

      - uses: camptocamp/initialise-gopass-summon-action@v2
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
          patterns: docker
        if: github.repository == 'camptocamp/docker-qgis-server'

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - run: make pull
      - run: make build
      - run: make run
      - run: make acceptance
      - run: (cd acceptance_tests; docker-compose logs)
        if: failure()

      - name: Publish
        run: c2cciutils-publish --type=rebuild --branch=${{ matrix.branch }}
